library(KernSmooth)
data <- read.table("../example_output/git/eur_test_prePRIMUS/eur_test_noDups_autosomal_merged_PCV_vals.txt")
all_kde <- bkde2D(data[,1-2],c(.01,.01),c(300,300))
pc1_min = min(all_kde$x1) - .01
pc1_max = max(all_kde$x1) + .01
pc2_min = min(all_kde$x2) - .01
pc2_max = max(all_kde$x2) + .01
ranges<-list(c(pc1_min,pc1_max),c(pc2_min,pc2_max))
pdf("../example_output/git/eur_test_prePRIMUS/eur_test_noDups_autosomal_merged_KDE_contours.pdf", height=8, width=10.5,family="mono")
par(mai = c(1,1,1,4), oma = c(1,1,1,1),xpd=T)
ASW = subset(data, V1=="ASW", select = c("V2","V3"))
ASW_kde <- bkde2D(ASW,c(0.02,0.02),c(300,300),ranges)
write.table(ASW_kde, file = "../example_output/git/eur_test_prePRIMUS/eur_test_noDups_autosomal_merged_ASW_kde.txt",row.names=F,col.names=F)
contour(ASW_kde$x1, ASW_kde$x2, ASW_kde$fhat,add=F,col='steelblue4')
CEU = subset(data, V1=="CEU", select = c("V2","V3"))
CEU_kde <- bkde2D(CEU,c(0.01,0.01),c(300,300),ranges)
write.table(CEU_kde, file = "../example_output/git/eur_test_prePRIMUS/eur_test_noDups_autosomal_merged_CEU_kde.txt",row.names=F,col.names=F)
contour(CEU_kde$x1, CEU_kde$x2, CEU_kde$fhat,add=T,col='red')
CHB = subset(data, V1=="CHB", select = c("V2","V3"))
CHB_kde <- bkde2D(CHB,c(0.008,0.008),c(300,300),ranges)
write.table(CHB_kde, file = "../example_output/git/eur_test_prePRIMUS/eur_test_noDups_autosomal_merged_CHB_kde.txt",row.names=F,col.names=F)
contour(CHB_kde$x1, CHB_kde$x2, CHB_kde$fhat,add=T,col='darkred')
CHD = subset(data, V1=="CHD", select = c("V2","V3"))
CHD_kde <- bkde2D(CHD,c(0.008,0.008),c(300,300),ranges)
write.table(CHD_kde, file = "../example_output/git/eur_test_prePRIMUS/eur_test_noDups_autosomal_merged_CHD_kde.txt",row.names=F,col.names=F)
contour(CHD_kde$x1, CHD_kde$x2, CHD_kde$fhat,add=T,col='green')
GIH = subset(data, V1=="GIH", select = c("V2","V3"))
GIH_kde <- bkde2D(GIH,c(0.003,0.003),c(300,300),ranges)
write.table(GIH_kde, file = "../example_output/git/eur_test_prePRIMUS/eur_test_noDups_autosomal_merged_GIH_kde.txt",row.names=F,col.names=F)
contour(GIH_kde$x1, GIH_kde$x2, GIH_kde$fhat,add=T,col='darkgreen')
JPT = subset(data, V1=="JPT", select = c("V2","V3"))
JPT_kde <- bkde2D(JPT,c(0.008,0.008),c(300,300),ranges)
write.table(JPT_kde, file = "../example_output/git/eur_test_prePRIMUS/eur_test_noDups_autosomal_merged_JPT_kde.txt",row.names=F,col.names=F)
contour(JPT_kde$x1, JPT_kde$x2, JPT_kde$fhat,add=T,col='slateblue1')
LWK = subset(data, V1=="LWK", select = c("V2","V3"))
LWK_kde <- bkde2D(LWK,c(0.008,0.008),c(300,300),ranges)
write.table(LWK_kde, file = "../example_output/git/eur_test_prePRIMUS/eur_test_noDups_autosomal_merged_LWK_kde.txt",row.names=F,col.names=F)
contour(LWK_kde$x1, LWK_kde$x2, LWK_kde$fhat,add=T,col='slateblue4')
MEX = subset(data, V1=="MEX", select = c("V2","V3"))
MEX_kde <- bkde2D(MEX,c(0.006,0.006),c(300,300),ranges)
write.table(MEX_kde, file = "../example_output/git/eur_test_prePRIMUS/eur_test_noDups_autosomal_merged_MEX_kde.txt",row.names=F,col.names=F)
contour(MEX_kde$x1, MEX_kde$x2, MEX_kde$fhat,add=T,col='sienna1')
MKK = subset(data, V1=="MKK", select = c("V2","V3"))
MKK_kde <- bkde2D(MKK,c(0.008,0.008),c(300,300),ranges)
write.table(MKK_kde, file = "../example_output/git/eur_test_prePRIMUS/eur_test_noDups_autosomal_merged_MKK_kde.txt",row.names=F,col.names=F)
contour(MKK_kde$x1, MKK_kde$x2, MKK_kde$fhat,add=T,col='sienna4')
TSI = subset(data, V1=="TSI", select = c("V2","V3"))
TSI_kde <- bkde2D(TSI,c(0.01,0.01),c(300,300),ranges)
write.table(TSI_kde, file = "../example_output/git/eur_test_prePRIMUS/eur_test_noDups_autosomal_merged_TSI_kde.txt",row.names=F,col.names=F)
contour(TSI_kde$x1, TSI_kde$x2, TSI_kde$fhat,add=T,col='black')
YRI = subset(data, V1=="YRI", select = c("V2","V3"))
YRI_kde <- bkde2D(YRI,c(0.008,0.008),c(300,300),ranges)
write.table(YRI_kde, file = "../example_output/git/eur_test_prePRIMUS/eur_test_noDups_autosomal_merged_YRI_kde.txt",row.names=F,col.names=F)
contour(YRI_kde$x1, YRI_kde$x2, YRI_kde$fhat,add=T,col='darkgoldenrod3')
all_data <- read.table("../example_output/git/eur_test_prePRIMUS/eur_test_noDups_autosomal_merged_PCV1vPCV2.txt",stringsAsFactors=FALSE,header=F)
data <- subset(all_data, V3 == 'eur_test')
points(data[,5],data[,6],col='blue',pch=4)
legend(x="left",inset=1.01,legend=c("eur_test","ASW","CEU","CHB","CHD","GIH","JPT","LWK","MEX","MKK","TSI","YRI"),text.col=c("blue","steelblue4","red","darkred","green","darkgreen","slateblue1","slateblue4","sienna1","sienna4","black","darkgoldenrod3"),fill=c("blue","steelblue4","red","darkred","green","darkgreen","slateblue1","slateblue4","sienna1","sienna4","black","darkgoldenrod3"),cex=1)
dev.off()
